pipeline {
  agent none
  
  stages {
     stage('Build et Tests unitaires') {
      agent any
      steps {  
	      echo 'Building and Unit tests'
        sh 'mvn -Dmaven.test.failure.ignore=true clean test' 
      }
      post { 
        always { 
            junit '**/target/surefire-reports/*.xml'
        }
        failure {
          mail body: 'It is very bad', from: 'oodoo@plb.fr', subject: 'Compilation or Unit test broken', to: 'david.thibau@gmail.com'
        }
      }
   }
stage('Parallel Stage') {
  parallel {
    stage('Intégration test') {
      agent any
       steps {  
           echo "Integration test"
           sh 'mvn -Pacceptance-tests verify -Dwebdriver.chrome.driver=/home/dthibau/Formations/Cucumber/MyWork/chromedriver_linux64/chromedriver -Dcucumber.filter.tags="@web"'
        }
    }
    stage('Quality analysis') {
      agent any
      steps {  
          echo "Analyse sonar"
          sh 'mvn clean verify sonar:sonar' 
      }
    }
  }
}

 
 
}
}
